### ISSUE TITLE
Do not store credentials into Git repository

### ISSUE THREAD

**Issue by fwouts** [zenclabs/jit#7]
Right now, the Jira API token is stored in `.jit/config.yaml` within the current Git repository.

A `.gitignore` is added along with it, so it won't be checked into Git (although the `.gitignore` must be).

However, that's not enough. For example, a Docker build may still include it.

A safer option may be to move the Jit credentials to `~/.jit`. This will also make it easier to configure once for all projects.

People who use multiple Jira hosts may complain, but we can find an alternative for them, e.g. with the ability to have several configurations they can switch between.

**Comment by jobwat** [comment]
💯 
Having the `.jit` config in the project folder force us to reconfigure for each repo... which is painful when using 20 repo from the same organisation
